---
# The variables file used by the playbooks in the ambari-server group.
# These don't have to be explicitly imported by vars_files: they are autopopulated.

repo_url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.7.3.0
ambari_version: 2.7.3.0
db: postgres
db_host: pandrade-1
db_name: ambari
db_username: ambari
db_password: bigdata
db_port: 5432