---

- hosts: ambari-server
  become: yes
  become_method: sudo
  tasks:

#   - name: Download ambari repo file
#      get_url:
#        url: '{{repo_url}}'
#        dest: /etc/yum.repos.d/ambari.repo
#        mode: 0644

    - name: Add the Ambari repository (yum)
      yum_repository:
        name: "ambari"
        description: "ambari Version - ambari-{{ ambari_version }}"
        baseurl: "{{ repo_url }}"
        file: 'ambari'
        state: present
        gpgcheck: yes
        gpgkey: "{{ repo_url }}/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins"

    - name: Install the ambari-server package
      package:
        name: ambari-server
        state: latest




    
