# Ansible role to deploy an Ambari client

---

- name: Add the Ambari repository (yum)
  yum_repository:
    name: "ambari"
    description: "ambari Version - ambari-{{ ambari_version }}"
    baseurl: "{{ repo_url }}"
    file: 'ambari'
    state: present
    enabled: 1
    gpgcheck: yes
    gpgkey: '{{key_url}}'

- name: Install the ambari-agent package
  package:
    name: ambari-agent
    state: latest

- name: Point agent to server
  lineinfile:
    path: /etc/ambari-agent/conf/ambari-agent.ini
    regexp: "hostname=localhost"
    line: "hostname={{ambari_server_hn}}"

- name: Restart ambari-agent
  systemd:
    name: ambari-agent
    state: restarted
    
